Play travis
Otus-DevOps-2021-11/SedovSG_infra pull request #2
Opened 2021-12-15 12:25 UTC by SedovSG

Сompleted the first homework assignment

2021-12-16 09:58 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз, оставил комментарий к файлу
Нужно починить тесты, дз отправляю на доработку

2021-12-16 09:58 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот сюда смотрим внимательно =)

2021-12-16 11:25 UTC, SedovSG commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Тест изначально был неправельным. Я думал, что так было и задумано. )

2021-12-17 07:57 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Не совсем =)

2021-12-17 07:57 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь апрув =)

2021-12-18 15:50 UTC, merged