Packer base
Otus-DevOps-2021-11/SedovSG_infra pull request #6
Opened 2021-12-26 19:56 UTC by SedovSG

Инструкции по запуску Packer в файле README.md

2021-12-26 19:58 UTC, SedovSG commented
Не понимаю для чего валидируется файл шаблона с переменными?

2021-12-27 16:51 UTC, mrgreyves requested changes
Здравствуйте!)
Конфиг пакера проверяется для того что бы удостовериться что он корректный
И соответственно корректно оработает, хотя у нас базовая проверка которая фактически проверяет синтаксис написания файла
Вам нужно поправить историю с ключом, нужно добавить фейковый ключик
ДЗ возвращаю на доработку

2021-12-27 19:30 UTC, SedovSG commented
Добавил фейковый ключ

2021-12-28 14:35 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув!)

2021-12-28 15:57 UTC, merged